// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaWpK6GXPl3IgAyJ8wPflA60wMnitEbKE',
    appId: '1:676830494143:web:fdd7ced46569660391f50a',
    messagingSenderId: '676830494143',
    projectId: 'testing-cli-9a918',
    authDomain: 'testing-cli-9a918.firebaseapp.com',
    storageBucket: 'testing-cli-9a918.appspot.com',
    measurementId: 'G-XH87T3L1FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuzMQNWgX0bd6w8TJNxFdXt8cEGcds5yQ',
    appId: '1:676830494143:android:6c8a4c027ee786f591f50a',
    messagingSenderId: '676830494143',
    projectId: 'testing-cli-9a918',
    storageBucket: 'testing-cli-9a918.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6JiH0ErwR97Knfm41DLJuDl6S51lGU2E',
    appId: '1:676830494143:ios:98c9cc530715670e91f50a',
    messagingSenderId: '676830494143',
    projectId: 'testing-cli-9a918',
    storageBucket: 'testing-cli-9a918.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6JiH0ErwR97Knfm41DLJuDl6S51lGU2E',
    appId: '1:676830494143:ios:98c9cc530715670e91f50a',
    messagingSenderId: '676830494143',
    projectId: 'testing-cli-9a918',
    storageBucket: 'testing-cli-9a918.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaWpK6GXPl3IgAyJ8wPflA60wMnitEbKE',
    appId: '1:676830494143:web:5744fde19d2c619b91f50a',
    messagingSenderId: '676830494143',
    projectId: 'testing-cli-9a918',
    authDomain: 'testing-cli-9a918.firebaseapp.com',
    storageBucket: 'testing-cli-9a918.appspot.com',
    measurementId: 'G-DBDK6G8N26',
  );
}
